In [1]:
import pandas as pd

In [2]:
from pathlib import Path

data_path = Path("data/hotel_bookings_cleaned-2.xlsx")
if not data_path.exists():
    data_path = Path("../data/hotel_bookings_cleaned-2.xlsx")

df = pd.read_excel(data_path)
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,total_nights,booking_value,booking_outcome
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,2,0,0.00,Showed Up
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,2,0,0.00,Showed Up
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,1,1,75.00,Showed Up
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,1,1,75.00,Showed Up
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.00,0,1,Check-Out,2015-07-03,2,2,196.00,Showed Up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87232,City Hotel,0,23,2017,August,35,30,2,5,2,...,Transient,96.14,0,0,Check-Out,2017-09-06,2,7,672.98,Showed Up
87233,City Hotel,0,102,2017,August,35,31,2,5,3,...,Transient,225.43,0,2,Check-Out,2017-09-07,3,7,1578.01,Showed Up
87234,City Hotel,0,34,2017,August,35,31,2,5,2,...,Transient,157.71,0,4,Check-Out,2017-09-07,2,7,1103.97,Showed Up
87235,City Hotel,0,109,2017,August,35,31,2,5,2,...,Transient,104.40,0,0,Check-Out,2017-09-07,2,7,730.80,Showed Up
87236,City Hotel,0,205,2017,August,35,29,2,7,2,...,Transient,151.20,0,2,Check-Out,2017-09-07,2,9,1360.80,Showed Up

In [3]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87237 entries, 0 to 87236
Data columns (total 36 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87237 non-null  object
 1   is_canceled                     87237 non-null  int64
 2   lead_time                       87237 non-null  int64
 3   arrival_date_year               87237 non-null  int64
 4   arrival_date_month              87237 non-null  object
 5   arrival_date_week_number        87237 non-null  int64
 6   arrival_date_day_of_month       87237 non-null  int64
 7   stays_in_weekend_nights         87237 non-null  int64
 8   stays_in_week_nights            87237 non-null  int64
 9   adults                          87237 non-null  int64
 10  children                        87237 non-null  int64
 11  babies                          87237 non-null  int64
 12  meal                            87237 non-null  object
 13  country                         87237 non-null  object
 14  market_segment                  87237 non-null  object
 15  distribution_channel            87237 non-null  object
 16  is_repeated_guest               87237 non-null  int64
 17  previous_cancellations          87237 non-null  int64
 18  previous_bookings_not_canceled  87237 non-null  int64
 19  reserved_room_type              87237 non-null  object
 20  assigned_room_type              87237 non-null  object
 21  booking_changes                 87237 non-null  int64
 22  deposit_type                    87237 non-null  object
 23  agent                           87237 non-null  float64
 24  company                         87237 non-null  float64
 25  days_in_waiting_list            87237 non-null  int64
 26  customer_type                   87237 non-null  object
 27  adr                             87237 non-null  float64
 28  required_car_parking_spaces     87237 non-null  int64
 29  total_of_special_requests       87237 non-null  int64
 30  reservation_status              87237 non-null  object
 31  reservation_status_date         87237 non-null  object
 32  total_guests                    87237 non-null  int64
 33  total_nights                    87237 non-null  int64
 34  booking_value                   87237 non-null  float64
 35  booking_outcome                 87237 non-null  object
dtypes: float64(4), int64(19), object(13)
memory usage: 24.0+ MB

(87237, 36)

## Feature Selection

In [4]:
# Dropping unwanted features
features = df.drop(columns=[
    'booking_value',
    'total_nights',
    'total_guests',
    'is_canceled',
    'reservation_status',
    'reservation_status_date',
    'arrival_date_day_of_month',
    'arrival_date_week_number',
    'country',
    'assigned_room_type',
    'company',
    'agent',
    'days_in_waiting_list',
    'booking_outcome',
    'required_car_parking_spaces',
    'deposit_type'
])

In [5]:
# Target variable
target = df['booking_value']

In [6]:
print("features shape:", features.shape)
print("target shape:", target.shape)

features shape: (87237, 20)
target shape: (87237,)

In [7]:
# Our selected predictor variables/features
features.columns

Index(['hotel', 'lead_time', 'arrival_date_year', 'arrival_date_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'booking_changes', 'customer_type', 'adr', 'total_of_special_requests'],
      dtype='object')

In [8]:
features.dtypes

hotel                              object
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                            int64
babies                              int64
meal                               object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
booking_changes                     int64
customer_type                      object
adr                               float64
total_of_special_requests           int64
dtype: object

In [9]:
features.dtypes.value_counts()

int64      12
object      7
float64     1
Name: count, dtype: int64

**We have some categorical variables listed as "object" datatype. So, we'll have to encode them using One-Hot Encoding**

## Encoding Categorical Variables

In [10]:
# Extracting the categorical variables
categorical_cols = features.select_dtypes(include='object').columns
categorical_cols

Index(['hotel', 'arrival_date_month', 'meal', 'market_segment',
       'distribution_channel', 'reserved_room_type', 'customer_type'],
      dtype='object')

In [11]:
# Encoding all the categorical variables automatically and dropping the first encoded variable from each to avoid multicolinearity
X= pd.get_dummies(features, columns=categorical_cols, drop_first=True)

In [12]:
X.shape

(87237, 52)

In [13]:
X.columns

Index(['lead_time', 'arrival_date_year', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes', 'adr',
       'total_of_special_requests', 'hotel_Resort Hotel',
       'arrival_date_month_August', 'arrival_date_month_December',
       'arrival_date_month_February', 'arrival_date_month_January',
       'arrival_date_month_July', 'arrival_date_month_June',
       'arrival_date_month_March', 'arrival_date_month_May',
       'arrival_date_month_November', 'arrival_date_month_October',
       'arrival_date_month_September', 'meal_FB', 'meal_HB', 'meal_SC',
       'meal_Undefined', 'market_segment_Complementary',
       'market_segment_Corporate', 'market_segment_Direct',
       'market_segment_Groups', 'market_segment_Offline TA/TO',
       'market_segment_Online TA', 'market_segment_Undefined',
       'distribution_channel_Direct', 'distribution_channel_GDS',
       'distribution_channel_TA/TO', 'distribution_channel_Undefined',
       'reserved_room_type_B', 'reserved_room_type_C', 'reserved_room_type_D',
       'reserved_room_type_E', 'reserved_room_type_F', 'reserved_room_type_G',
       'reserved_room_type_H', 'reserved_room_type_L', 'reserved_room_type_P',
       'customer_type_Group', 'customer_type_Transient',
       'customer_type_Transient-Party'],
      dtype='object')

**From the output of the code, we can see:**
- *the categorical variables were encoded.*
- *the first dummy variables for each categorical column were dropped*
- *the original categorical columns were dropped*

**The dummy variables dropped include:**
- *hotel_City Hotel*
- *arrival_date_month_April*
- *meal_BB*
- *market_segment_Aviation*
- *distribution_channel_Corporate*
- *reserved_room_type_A*
- *customer_type_Contract*

In [14]:
y=target

In [15]:
y.shape

(87237,)

In [16]:
y.head()

0      0.0
1      0.0
2     75.0
3     75.0
4    196.0
Name: booking_value, dtype: float64

In [17]:
X.describe()

,lead_time,arrival_date_year,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,adr,total_of_special_requests
count,87237.000000,87237.000000,87237.000000,87237.000000,87237.000000,87237.000000,87237.000000,87237.000000,87237.000000,87237.000000,87237.000000,87237.000000,87237.000000
mean,79.970551,2016.210347,1.004528,2.623738,1.878996,0.138783,0.010844,0.038562,0.030411,0.184027,0.268441,106.406667,0.698843
std,86.065217,0.686044,1.027395,2.039866,0.622189,0.456066,0.113699,0.192549,0.369344,1.732963,0.710581,51.795838,0.831994
min,0.000000,2015.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.000000,2016.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,72.240000,0.000000
50%,49.000000,2016.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,98.100000,0.000000
75%,125.000000,2017.000000,2.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,134.000000,1.000000
max,737.000000,2017.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,18.000000,392.000000,5.000000

In [18]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (87237, 52)
y shape: (87237,)

In [19]:
X.dtypes.value_counts()

bool       39
int64      12
float64     1
Name: count, dtype: int64

**We've successfully encoded all our categorical variables. Now, we move to splitting our dataset**

## Train-Test Split

*Why is train-test split necessary?*
- Training set learns relationships between booking features and revenue
- Test set simulates real-world prediction (data the model has never seen)
- Prevents overfitting (model memorizing rather than generalizing)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
# Verify the split
print("X_train shape: ", X_train.shape)
print("X_test shape: ", X_test.shape)

print("y_train shape: ", y_train.shape)
print("y_test shape: ", y_test.shape)

X_train shape:  (69789, 52)
X_test shape:  (17448, 52)
y_train shape:  (69789,)
y_test shape:  (17448,)

In [23]:
X_train.dtypes.value_counts()

bool       39
int64      12
float64     1
Name: count, dtype: int64

## Scaling the Numeric Features

### Why do we need to scale the numeric featurs?
- *The model may give more importance to features with larger numbers, therefore, scaling puts features on a comparable scale.*
- **Note:** *However, we do not scale the encoded variables (now Boolean datatypes) because scaling them doesn't add much value and makes interpretation harder.*

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler = StandardScaler()

In [26]:
X_train.describe()

,lead_time,arrival_date_year,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,adr,total_of_special_requests
count,69789.000000,69789.000000,69789.000000,69789.000000,69789.000000,69789.000000,69789.000000,69789.000000,69789.000000,69789.000000,69789.000000,69789.000000,69789.000000
mean,79.918669,2016.211624,1.003611,2.625285,1.877545,0.139148,0.010876,0.038502,0.030621,0.188325,0.269412,106.310439,0.699895
std,86.178710,0.686643,1.028044,2.041545,0.638075,0.457134,0.115485,0.192406,0.379626,1.773021,0.714410,51.693196,0.832221
min,0.000000,2015.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.000000,2016.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,72.140000,0.000000
50%,49.000000,2016.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,98.100000,0.000000
75%,125.000000,2017.000000,2.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,134.000000,1.000000
max,737.000000,2017.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,18.000000,392.000000,5.000000

In [27]:
numeric_cols = X.select_dtypes(['int', 'float']).columns
numeric_cols

Index(['lead_time', 'arrival_date_year', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes', 'adr',
       'total_of_special_requests'],
      dtype='object')

In [28]:
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

In [29]:
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

**We scale (transform) both train and test feature data (X) but we fit only the training data (X-train), so the scaler learns from the training data only and not the test data.**

In [30]:
X_train.describe()

,lead_time,arrival_date_year,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,adr,total_of_special_requests
count,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04,6.978900e+04
mean,-1.018130e-18,6.394620e-14,8.318122e-17,2.667501e-17,3.461642e-17,-5.599715e-18,1.496651e-17,5.487721e-17,1.343932e-17,7.126910e-19,-8.145040e-18,5.080469e-17,-4.235421e-17
std,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00,1.000007e+00
min,-9.273664e-01,-1.764574e+00,-9.762408e-01,-1.285940e+00,-2.942534e+00,-3.043940e-01,-9.417440e-02,-2.001088e-01,-8.066119e-02,-1.062177e-01,-3.771140e-01,-2.056580e+00,-8.410030e-01
25%,-7.997238e-01,-3.082026e-01,-9.762408e-01,-7.961110e-01,1.919142e-01,-3.043940e-01,-9.417440e-02,-2.001088e-01,-8.066119e-02,-1.062177e-01,-3.771140e-01,-6.610286e-01,-8.410030e-01
50%,-3.587764e-01,-3.082026e-01,-3.512410e-03,-3.062824e-01,1.919142e-01,-3.043940e-01,-9.417440e-02,-2.001088e-01,-8.066119e-02,-1.062177e-01,-3.771140e-01,-1.588313e-01,-8.410030e-01
75%,5.231182e-01,1.148169e+00,9.692160e-01,6.733749e-01,1.919142e-01,-3.043940e-01,-9.417440e-02,-2.001088e-01,-8.066119e-02,-1.062177e-01,-3.771140e-01,5.356558e-01,3.606094e-01
max,7.624691e+00,1.148169e+00,1.750560e+01,2.320549e+01,8.325479e+01,2.157116e+01,8.649788e+01,4.997282e+00,6.840828e+01,4.050272e+01,2.481868e+01,5.526677e+00,5.167059e+00

In [31]:
X_train.dtypes.value_counts()

bool       39
float64    13
Name: count, dtype: int64

In [32]:
X_train.shape

(69789, 52)

## K-Fold Cross-Validation

### Evaluate model stability

In [33]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [34]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    model,
    X_train,
    y_train,
    cv=5,
    scoring='r2'
)

In [35]:
print(cv_scores)
print(cv_scores.mean())
print(cv_scores.std())

[0.85032821 0.85272244 0.86122345 0.84606841 0.85571259]
0.8532110204390874
0.005099472108110171

## Model Training

In [36]:
model.fit(X_train, y_train)

LinearRegression()

In [37]:
y_pred = model.predict(X_test)
y_pred

array([904.52974371, 591.75382998, 316.20088943, ..., 247.32521651,
       214.270334  , 210.21960453])

In [38]:
print("y_test\t y_pred")

for actual, pred in zip(y_test[:20], y_pred[:20]):
    print(f"{actual:.2f}\t{pred:.2f}")

y_test	 y_pred
929.20	904.53
601.20	591.75
327.00	316.20
278.00	361.86
55.00	-29.69
384.00	421.34
633.00	664.03
212.00	207.98
452.16	410.63
1171.68	983.94
79.00	29.50
251.00	629.41
318.60	276.21
240.30	177.03
190.04	239.65
1483.20	1197.80
379.20	423.50
224.00	217.04
359.55	231.22
520.00	470.62

In [39]:
model.score(X_test, y_test)

0.8475663203595679

## Model Evaluation

### r2 Score (Predicted score) vs Cross Validation Score (Expected Score)

**r2 means coefficient of determination and is equal to the proportion of revenue variance explained by your features, ranging from 0-1**

In [40]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
r2

0.8475663203595679

In [41]:
print("Expected Score: ", cv_scores.mean(),
      "\nPredicted Score: ", r2
)

Expected Score:  0.8532110204390874
Predicted Score:  0.8475663203595679

**We see that our model's test data score (predicted) is very close to the train data score (expected) showing the model's good performance - no overfitting or leakage**

### Mean Absolute Error

**MAE means the average absolute difference between predicted and actual revenue**

In [42]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)
print(mae)

79.23629119717005

**This means that revenue predictions could be off by ±$79 on average per booking**

### Root Mean Square Error

In [43]:
from sklearn.metrics import root_mean_squared_error

rmse = root_mean_squared_error(y_test, y_pred)
print(rmse)

143.8842765213528

**MAE treats all errors equally, RMSE punishes large errors heavily.**

**Since RMSE is much larger than MAE, we can infer that the model is making some large errors somewhere. This means most predictions are reasonably close, but a few bookings are being predicted very poorly.**